# Generated by Django 4.2.2 on 2023-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=100)),
                ('matichen_broj', models.CharField(max_length=13)),
                ('grad', models.CharField(max_length=50)),
            ],
        ),
    ]
