# Generated by Django 4.2.2 on 2023-06-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prva_aplikacija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lice',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lice',
            name='godini',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lice',
            name='matichen_broj',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
