# Generated by Django 4.2.2 on 2023-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prva_aplikacija', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
