# Generated by Django 4.2.2 on 2023-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prva_aplikacija', '0004_alter_post_created_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
