# Generated by Django 4.2.2 on 2023-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prva_aplikacija', '0006_klient_naracka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dali_ima_nagrade', models.BooleanField()),
            ],
        ),
    ]
