# Generated by Django 4.2.2 on 2023-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prva_aplikacija', '0007_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('zanr', models.CharField(max_length=50)),
                ('godina', models.IntegerField()),
                ('vremetranje_minuti', models.IntegerField()),
                ('dali_ima_nagrade', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
