# Generated by Django 4.2.2 on 2023-06-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient_Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefonski_broj', models.CharField(max_length=30)),
                ('adresa_na_ziveenje', models.CharField(max_length=100)),
                ('vraboten_von', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transakciska_Smetka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sostojba', models.CharField(max_length=50)),
                ('datum_na_kreiranje', models.DateTimeField(auto_now_add=True)),
                ('posledna_transakcija', models.DateTimeField(auto_now=True)),
                ('Klient_Banka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banka.klient_banka')),
            ],
        ),
    ]
