# Generated by Django 4.2.2 on 2023-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klient_banka',
            old_name='vraboten_von',
            new_name='vraboten_vo',
        ),
        migrations.AddField(
            model_name='klient_banka',
            name='dali_vraboten',
            field=models.BooleanField(default=0),
        ),
    ]
