# Generated by Django 4.2.2 on 2023-06-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banka', '0004_rename_klient_banka_klient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klient',
            old_name='dali_vraboten',
            new_name='dali_e_vraboten',
        ),
    ]
